@startuml

!define RECTANGLE class

package "Front-End Application" {
    RECTANGLE ComponentA {
        +specificRequestA()
    }
    RECTANGLE ComponentB {
        +specificRequestB()
    }
    RECTANGLE ComponentC {
        +specificRequestC()
    }
    RECTANGLE RoleBasedRouter {
        +checkAccess(component, userRole): boolean 
    }
    RECTANGLE HTTPInterceptor {
        +interceptRequest(): append JWT
    }
    RECTANGLE UserInterface {
        +login(username, password)
        +register(firstName, lastName, email, password)
        +deleteAccount(userID, token): boolean 
        +receiveData()
    }
}

package "ASP NET Core C# Authentication Service" {
    RECTANGLE AuthenticationBuilder {
        +configureJWTAuthentication() 
    }
    RECTANGLE UserController {
        +Login(LoginUserDTO):Task<TokenDto>
        +Register(CreateUserDto): Task<RegisteredDTO>
        +DeleteAcc(AccountDeletionDto): Task<IdentityResult>
    }
    RECTANGLE UserService {
        +Login(LoginUserDto): Task<TokenDto>
        +Register(CreateUserDto): Task<RegisteredDTO>
        +DeleteAccount(AccountDeletionDto): Task<IdentityResult>
    }
    RECTANGLE JWTService {
        +createToken(ApplicationUser): Task<TokenDto>
    }
}

package "Nodejs Backend Service" {
    RECTANGLE JWTMiddleware {
        +validateJWT(token)
    }
    RECTANGLE ResourceController {
        +handleRequest()
        +accessProtectedResources()
    }
}

database "Database" {
    folder "User Credentials" {
    }
    folder "Other Data" {
    }
}

UserInterface --> RoleBasedRouter
RoleBasedRouter --> ComponentA
RoleBasedRouter --> ComponentB
RoleBasedRouter --> ComponentC
ComponentA --> HTTPInterceptor : intercepts all requests
ComponentB --> HTTPInterceptor : intercepts all requests
ComponentC --> HTTPInterceptor : intercepts all requests
UserInterface --> UserController : requests login/register/delete
UserController --> UserService : validate & manage users
UserService --> Database : store/retrieve/delete user data
UserController --> JWTService : create JWT
AuthenticationBuilder ..> Database : retrieve signing key
HTTPInterceptor --> JWTMiddleware : sends requests with JWT
JWTMiddleware --> ResourceController : on valid JWT
ResourceController ..> Database : access data

@enduml
