@startuml
autonumber
'hide footbox
actor "User" as admin

participant "<<Frontend>>\n(CreateTask Component)" as f
participant "<<Backend>>\n(Task Controller)" as c

activate admin

admin -> f: create a task
activate f

f --> admin: request necessary data()
admin -> f : insert all the data
activate c
f -> c: POST createTask{taskDto}

alt successful case
    c --> f: success message
    f --> admin: show success message
else
    c --> f: failure message
    f --> admin: show failure message
end
deactivate c
deactivate f
@enduml