@startuml sd

participant Route as route
participant InterfaceEdificioController as ictrl
participant EdificioController as ctrl
participant InterfaceEdificioService as isvc
participant EdificioService as svc
participant InterfaceEdificioRepo as irepo
participant EdificioRepo as repo
participant EdificioMapper as mapper
participant InterfaceEdificioPersistence as ischema
participant EdificioSchema as schema
participant ConfigurationFile as conf
participant Edificio as model

activate route
route -> ictrl : /loadFloorMap
activate ictrl
ictrl -> ctrl : loadFloorMap(req, res, next)
activate ctrl
ctrl -> conf : injeta o serviço do edificio
activate conf
conf --> ctrl
deactivate conf
ctrl -> isvc : loadFloorMap(IEdificioDTO)
activate isvc
isvc -> svc : loadFloorMap(IEdificioDTO)
activate svc
svc -> conf : injeta o repositório do edificio
activate conf
conf --> svc
deactivate conf
svc -> repo : edificio = findByCodigo(codigo)
activate repo
repo --> svc
deactivate repo
alt edificio não encontrado
    svc --> isvc : Edificio não encontrado
    isvc --> ctrl
    ctrl --> ictrl : Envia um código 404 (NOT FOUND)
    ictrl --> route
else
    svc -> model : edificio atualiza os campos
    activate model
    model --> svc
    deactivate model
    svc -> irepo : edificio = save(edificio)
    activate irepo
    irepo -> repo : save(edificio)
    activate repo
    repo -> conf : injeta o schema do edificio
    activate conf
    conf --> repo
    deactivate conf
    repo -> mapper : toPersistence(edificio)
    activate mapper
    mapper --> repo
    deactivate mapper
    repo -> ischema : create(edificioCreated)
    activate ischema 
    ischema -> schema : create(edificioCreated)
    activate schema
    schema --> ischema
    deactivate schema
    ischema --> repo
    deactivate ischema
    repo -> mapper : toDomain(edificioCreated)
    activate mapper
    mapper --> repo
    deactivate mapper
    repo --> irepo
    deactivate repo
    irepo --> svc
    deactivate irepo
    svc -> mapper : toDTO(edificio)
    activate mapper
    mapper --> svc
    deactivate mapper
    svc --> isvc
    deactivate svc
    isvc --> ctrl
    deactivate isvc
    ctrl --> ictrl : Envia um código 201 (POST)
    ictrl --> ctrl : Escolher um piso
    ctrl -> ictrl : /chooseFloor
    ictrl --> ctrl : Escolher um piso
    ctrl -> isvc : chooseFloor(IEdificioDTO)
    isvc --> svc : chooseFloor(IEdificioDTO)
    activate svc
    svc -> svc : Processar escolha do piso
    svc --> isvc : Resposta
    deactivate svc
    isvc --> ctrl
    ctrl --> ictrl
end

deactivate ctrl
ictrl --> route
deactivate ictrl
deactivate route

@enduml